name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: corretto
            java-version: 17
      - name: Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget https://github.com/jedisct1/minisign/releases/download/0.11/minisign-0.11-linux.tar.gz
      - run: tar -xzvf minisign-0.11-linux.tar.gz
      - run: mv minisign-linux/x86_64/minisign .
      - run: minisign -Vm ./test/test.txt -p ./test/minisign.pub
